---
settings:
  name: ONTAP FLI
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAP FLI documentos
    url: "/index.html"
  - section: release-notes
  - section: san-migration
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
