---
permalink: san-migration/concept_lun_requirements_and_limitations.html 
sidebar: sidebar 
keywords: lun, requirements, limitations 
summary: Os LUNs devem atender aos seguintes requisitos antes de iniciar uma migração FLI. 
---
= Requisitos e limitações do LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os LUNs devem atender aos seguintes requisitos antes de iniciar uma migração FLI.

* O FLI requer pelo menos uma porta FC em cada controlador e que OS LUNs migrem diretamente no modo Iniciador.
* O LUN estrangeiro deve ser marcado como estrangeiro no array de destino para evitar atribuições do ONTAP.
* O LUN estrangeiro deve estar em um relacionamento de importação antes de iniciar a importação.
* O LUN deve ter o mesmo tamanho que o LUN estrangeiro. Esse requisito é atendido durante as etapas de criação do LUN.
* O tamanho do bloco LUN estrangeiro deve ser de 512 bits. Os LUNs da NetApp suportam apenas tamanho de bloco de 512 bits.
* O LUN não deve estar em expansão ou em contratação.
* O LUN deve ser mapeado para pelo menos um grupo.
* O LUN da NetApp deve ser colocado offline antes de se criar uma relação. No entanto, após a criação da relação LUN, ela pode ser reativada em caso de FLI online.




== Limitações

* Todas as migrações estão no nível LUN.
* O FLI suporta apenas conexões Fibre Channel (FC).
* O FLI não suporta conexões iSCSI diretamente. Para que LUNs iSCSI sejam migrados usando FLI, o tipo LUN deve ser alterado para FC. Após a conclusão da migração, o tipo de LUN é alterado novamente para iSCSI.

