---
permalink: san-migration/concept_target_and_initiator_port_zoning.html 
sidebar: sidebar 
keywords: target, initiator, port, zoning 
summary: A migração DO FLI requer que LUNs de armazenamento de origem sejam acessados pelo armazenamento NetApp. Isto é conseguido através do zoneamento de portas de destino de armazenamento de origem com portas de iniciador de armazenamento de destino. 
---
= Zoneamento de porta de destino e iniciador para migrações ONTAP FLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A migração FLI exige que os LUNs de origem do array externo sejam acessados pelo armazenamento NetApp . Isso é feito por meio do zoneamento das portas de destino do armazenamento de origem com as portas iniciadoras do armazenamento de destino NetApp .

As zonas de storage para host de origem existentes não são modificadas e são desativadas após a migração. As zonas de armazenamento de host para destino são criadas para permitir o acesso de LUNs migrados do armazenamento de destino pelo host.

Um cenário de migração padrão usando FLI requer quatro zonas distintas:

* Zona 1: Armazenamento de origem para armazenamento de destino (tecido de Produção A)
* Zona 2: Armazenamento de origem para armazenamento de destino (tecido de produção B)
* Zona 3: Armazenamento do host para o destino (malha de Produção A)
* Zona 4: Anfitrião ao armazenamento de destino (tecido de produção B)


Siga estas práticas recomendadas de zoneamento:

* Não misture portas de destino de armazenamento de origem e portas de destino de armazenamento de destino na mesma zona.
* Não misture portas do iniciador de armazenamento de destino e portas de host na mesma zona.
* Não misture portas de destino de armazenamento e iniciador na mesma zona.
* Zona com pelo menos duas portas de cada controlador para redundância.
* A NetApp recomenda um único iniciador e um zoneamento de destino único.


[NOTE]
====
Depois de zonear as portas de destino de armazenamento de origem com as portas do iniciador de armazenamento de destino, o armazenamento de origem será visível no armazenamento de destino usando o comando show do storage.quando o storage array for descoberto pela primeira vez, os controladores NetApp podem não mostrar o array automaticamente. Corrija isso redefinindo a porta do switch onde as portas do iniciador ONTAP estão conetadas.

====
Um cenário de migração padrão usando FLI requer quatro zonas distintas. Você deve incluir portas específicas em cada zona.

* Zona 1: Armazenamento de origem para armazenamento de destino (tecido de Produção A)
+
A zona 1 deve conter todos os iniciadores de armazenamento de destino em todos os nós e todas as portas de destino de armazenamento de origem na estrutura A. os membros da zona incluem:

+
** ONTAP -- Node1 -- 0a
** ONTAP -- Node2 -- 0a
** AMS2100 -- Ctrl0 -- 0a
** AMS2100 -- Ctrl1 -- 1a


* Zona 2: Armazenamento de origem para armazenamento de destino (tecido de produção B)
+
A zona 2 deve conter todas as portas do iniciador de armazenamento de destino em todos os nós e todas as portas de destino de armazenamento de origem na malha B. os membros da zona 2 incluem:

+
** ONTAP -- Node1 -- 0b
** ONTAP -- Node2 -- 0b
** AMS2100 -- Ctrl0 -- 0e
** AMS2100 -- Ctrl1 -- 1e


* Zona 3: Armazenamento do host para o destino (malha de Produção A)
+
A zona 3 deve conter a porta 1 do adaptador de barramento do host (HBA) e as portas do controlador de destino na malha de produção A. os membros da zona 3 incluem:

+
** ONTAP -- lif1
** ONTAP -- lif3
** Host -- HBA0


* Zona 4: Anfitrião ao armazenamento de destino (tecido de produção B)
+
A zona 4 deve conter a porta HBA 2 e as portas do controlador de destino na malha de produção B. os membros da zona 4 incluem:

+
** ONTAP -- lif2
** ONTAP -- lif4
** Host -- HBA1



