---
permalink: san-migration/concept_fli_zoning_requirements.html 
sidebar: sidebar 
keywords: fli, zoning, requirements 
summary: Um cenário de migração padrão usando FLI requer quatro zonas distintas. Você deve incluir portas específicas em cada zona. 
---
= Requisitos de zoneamento do FLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um cenário de migração padrão usando FLI requer quatro zonas distintas. Você deve incluir portas específicas em cada zona.

* Zona 1: Armazenamento de origem para armazenamento de destino (tecido de Produção A)
+
A zona 1 deve conter todos os iniciadores de armazenamento de destino em todos os nós e todas as portas de destino de armazenamento de origem na estrutura A. os membros da zona incluem:

+
** ONTAP -- Node1 -- 0a
** ONTAP -- Node2 -- 0a
** AMS2100 -- Ctrl0 -- 0a
** AMS2100 -- Ctrl1 -- 1a


* Zona 2: Armazenamento de origem para armazenamento de destino (tecido de produção B)
+
A zona 2 deve conter todas as portas do iniciador de armazenamento de destino em todos os nós e todas as portas de destino de armazenamento de origem na malha B. os membros da zona 2 incluem:

+
** ONTAP -- Node1 -- 0b
** ONTAP -- Node2 -- 0b
** AMS2100 -- Ctrl0 -- 0e
** AMS2100 -- Ctrl1 -- 1e


* Zona 3: Armazenamento do host para o destino (malha de Produção A)
+
A zona 3 deve conter a porta 1 do adaptador de barramento do host (HBA) e as portas do controlador de destino na malha de produção A. os membros da zona 3 incluem:

+
** ONTAP -- lif1
** ONTAP -- lif3
** Host -- HBA0


* Zona 4: Anfitrião ao armazenamento de destino (tecido de produção B)
+
A zona 4 deve conter a porta HBA 2 e as portas do controlador de destino na malha de produção B. os membros da zona 4 incluem:

+
** ONTAP -- lif2
** ONTAP -- lif4
** Host -- HBA1



