---
permalink: san-migration/concept_using_fli_to_import_luns_into_all_flash.html 
sidebar: sidebar 
keywords: use, foreign lun import, import luns, aff 
summary: A partir do ONTAP 9.1, o AFF oferece suporte ao FLI. Você pode usar o FLI para importar LUNs de outros arrays diretamente para clusters ONTAP . 
---
= Usando a importação de LUN estrangeiro para importar LUNs para o AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.1, o AFF oferece suporte ao FLI. Você pode usar o FLI para importar LUNs de outros arrays diretamente para clusters ONTAP .

A partir do ONTAP 8.3.2, a AFF pode oferecer suporte à FLI com uma Solicitação de Variação de Processo (PVR) aprovada. Entre em contato com sua equipe de contas da NetApp para que o PVR seja submetido para aprovação. Após a aprovação, o solicitante, geralmente um Engenheiro de Sistemas da NetApp , receberá uma carta de aprovação com instruções para habilitar a funcionalidade FLI.

Para versões do software ONTAP anteriores à 8.3.2, será necessário preparar as importações FLI para um par HA não- AFF no mesmo cluster que o AFF. Após a conclusão da migração, você poderá usar operações não disruptivas (NDO), como movimentação de volumes ou LUNs, para mover os LUNs migrados para o AFF. Se o seu cluster AFF não tiver nenhum nó que não seja AFF , converse com sua equipe de contas sobre a possibilidade de pegar emprestado equipamentos de transição para viabilizar isso.
