---
permalink: san-migration/task_fli_offline_verifying_migration_results.html 
sidebar: sidebar 
keywords: fli offline, verify, migration, results 
summary: Um trabalho de verificação é opcional, mas recomendado. É uma comparação bloco a bloco das LUNs de origem e destino. Verifique se os trabalhos demoram quase o mesmo ou um pouco mais do que o tempo de migração. 
---
= Verifique os resultados da migração offline do ONTAP FLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Após a migração de um LUN do array externo para o seu sistema de armazenamento ONTAP , o FLI pode realizar uma comparação bloco a bloco dos LUNs de origem e destino para verificar se a migração foi concluída e precisa. A verificação da migração leva aproximadamente o mesmo tempo (ou um pouco mais) que a migração.

Uma verificação de migração não é necessária, mas é altamente recomendada.

.Sobre esta tarefa
A partir do ONTAP 9.17.1, a migração de dados de LUNs externos usando a migração offline FLI é suportada comlink:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Sistemas ASA r2"^]. Os sistemas ASA r2 diferem de outros sistemas ONTAP (ASA, AFF e FAS) na implementação de sua camada de armazenamento. Em sistemas ASA r2, os volumes são criados automaticamente quando uma unidade de armazenamento (LUN ou namespace) é criada. volume contém apenas uma unidade de armazenamento. Portanto, para sistemas ASA r2, não é necessário incluir o nome do volume no campo.  `-path` opção ao criar o LUN; você deve incluir o caminho da unidade de armazenamento.

.Passos
. Inicie a verificação da migração do LUN.
+
[source, cli]
----
lun import verify start -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Este exemplo mostra o comando para iniciar a verificação de migração de LUN para LUNs chamados *bootlun*, *fdrive* e *gdrive* no volume *winvol* e no SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/gdrive
----
. Monitore o status da verificação.
+
[source, cli]
----
lun import show -vserver <SVM_name> -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, estimated-remaining-duration
----
+
Este exemplo mostra o comando para monitorar o status de verificação do SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration

vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     in_progress       57               -               4194304      00:01:19
datamig 83017542000F /vol/winvol/gdrive started     in_progress       40               -               6291456      00:02:44
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     in_progress       8                -               41943040     00:20:29
3 entries were displayed.
----
+
Você pode executar o mesmo comando para acompanhar o progresso da verificação. O *estado-operacional* exibe o status *concluído* quando a tarefa de verificação é concluída com sucesso.

. Pare a verificação do LUN.
+
[source, cli]
----
lun import verify stop -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Este exemplo mostra o comando para interromper a verificação do LUN para o SVM *datamig*.

+
[listing]
----
DataMig-ontap::*> lun import verify stop -vserver datamig -path /vol/esxvol/winrdmplun
----
+
A verificação da importação do LUN deve ser explicitamente interrompida antes de colocar o LUN novamente online. Caso contrário, o  `lun online` O comando falha. Esta etapa deve ser executada manualmente, mesmo que o status indique que a verificação foi concluída.



.O que vem a seguir?
link:remove-lun-import-relationship-offline.html["Remover o relacionamento de importação do LUN"] .
