---
permalink: san-migration/task_fli_offline_importing_the_data.html 
sidebar: sidebar 
keywords: fli offline, import data 
summary: Estas etapas descrevem como importar os dados do LUN de origem para o LUN de destino. 
---
= FLI offline: Importando os dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Estas etapas descrevem como importar os dados do LUN de origem para o LUN de destino.

.Passos
. Inicie a importação de migração.
+
[listing]
----
DataMig-cmode::*> lun import start –vserver datamig –path /vol/winvol/bootlun

DataMig-cmode::*> lun import start –vserver datamig –path /vol/winvol/fdrive

DataMig-cmode::*> lun import start –vserver datamig –path /vol/winvol/gdrive
----
. Monitorize o progresso da importação. Você pode comparar o progresso que está vendo aqui com as estimativas de desempenho de migração desenvolvidas após a execução das migrações de teste.
+
[listing]
----
DataMig-cmode::*> lun import show –vserver datamig –fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration
vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     completed         100              4194304         4194304      -
datamig 83017542000F /vol/winvol/gdrive started     completed         100              6291456         6291456      -
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     in_progress       83               35107077        41943040     00:00:48
3 entries were displayed.
----
. Verifique se o trabalho de importação foi concluído com êxito.
+
[listing]
----
DataMig-cmode::*> lun import show –vserver datamig –fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration
vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     completed         100              4194304         4194304      -
datamig 83017542000F /vol/winvol/gdrive started     completed         100              6291456         6291456      -
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     completed         100
3 entries were displayed.
----

